version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: movie_collection         
      POSTGRES_USER: movie_controler         
      POSTGRES_PASSWORD: postgres             
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
