version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis  # Add Redis dependency
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine  # Using the lightweight Alpine image for Redis
    ports:
      - "6379:6379"  # Redis default port
